import type { ExportFilter } from './tableExport';
import { escapePrintHtml } from './tableExport';

const impexLogoUrl = '/brand/impex-engineering-logo.jpeg';
const thortexLogoUrl = '/brand/thortex-logo.jpeg';

function getCompanyInfo() {
  try {
    const raw = localStorage.getItem('company_info');
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

export function printHtml(title: string, bodyHtml: string) {
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow?.document;
  if (!doc) return;

  const company = getCompanyInfo();
  const companyHtml = company
    ? `
      <div class="company">
        <div class="company-name">${company.name || ''}</div>
        <div class="company-meta">${company.address || ''}</div>
        <div class="company-meta">${company.phone || ''}</div>
        <div class="company-meta">${company.email || ''}</div>
        <div class="company-meta">${company.website || ''}</div>
        <div class="company-meta">${company.tin || ''}</div>
      </div>
    `
    : '';

  doc.open();
  doc.write(`
    <html>
      <head>
        <title>${title}</title>
        <style>
          @page { size: auto; margin: 8mm; }
          body { font-family: Arial, sans-serif; color: #111; margin: 0; }
          .page { padding: 0; }
          .header { display: grid; grid-template-columns: 1fr 1.25fr; gap: 16px; align-items: flex-start; border-bottom: 1px solid #e5e7eb; padding-bottom: 12px; margin-bottom: 16px; }
          .brand-logos { display: flex; align-items: center; gap: 12px; }
          .brand-logo { display: flex; align-items: center; justify-content: center; overflow: hidden; border-radius: 6px; background: #fff; }
          .brand-logo.impex { width: 86px; height: 64px; padding: 8px; }
          .brand-logo.thortex { width: 138px; height: 64px; padding: 10px 14px; }
          .brand-logo img { width: 100%; height: 100%; object-fit: contain; }
          .company { font-size: 12px; color: #111; line-height: 1.35; text-align: right; }
          .company-name { font-weight: bold; font-size: 13px; letter-spacing: 0.2px; }
          .company-meta { margin-top: 2px; }
          h1 { font-size: 22px; margin: 6px 0 10px; }
          h2 { font-size: 16px; margin: 8px 0 6px; }
          h3 { font-size: 13px; margin: 8px 0 6px; }
          .doc-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin: 10px 0 12px; font-size: 12px; }
          .doc-meta div { color: #444; }
          table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 12px; }
          th, td { border-bottom: 1px solid #e5e7eb; padding: 8px 6px; }
          th { text-align: left; font-weight: 600; background: #f9fafb; }
          thead { display: table-header-group; }
          tr { break-inside: avoid; page-break-inside: avoid; }
          .meta { margin: 4px 0; font-size: 12px; color: #555; }
          .meta-inline { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
          .meta-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 6px 16px; margin: 10px 0 12px; }
          .meta-full { grid-column: 1 / -1; }
          .total { text-align: right; font-weight: bold; margin-top: 12px; }
          .footer { border-top: 1px solid #e5e7eb; margin-top: 10px; padding-top: 8px; font-size: 11px; color: #666; }
          .doc-label { font-weight: 600; color: #111; }
          .doc-code { border: 1px dashed #cbd5f5; background: #f8fafc; padding: 4px 8px; font-size: 12px; display: inline-block; vertical-align: middle; }
          .print-sheet { break-after: page; page-break-after: always; }
          .print-sheet:last-child { break-after: auto; page-break-after: auto; }
          .print-sheet-footer { display: flex; justify-content: space-between; gap: 12px; border-top: 1px solid #e5e7eb; margin-top: 12px; padding-top: 7px; font-size: 10px; color: #666; }
          .print-table-meta { margin-bottom: 10px; font-size: 11px; color: #555; }
          .print-table-meta div { margin-top: 2px; }
        </style>
      </head>
      <body>
        <div class="page">
          <div class="header">
            <div class="brand-logos">
              <div class="brand-logo impex">
                <img src="${impexLogoUrl}" alt="Impex Engineering Logo" />
              </div>
              <div class="brand-logo thortex">
                <img src="${thortexLogoUrl}" alt="Thortex Philippines Logo" />
              </div>
            </div>
            ${companyHtml}
          </div>
          ${bodyHtml}
        </div>
        <div class="footer">
          Generated by Impex Engineering - ${new Date().toLocaleString()}
        </div>
      </body>
    </html>
  `);
  doc.close();
  iframe.contentWindow?.focus();
  setTimeout(() => {
    iframe.contentWindow?.print();
    document.body.removeChild(iframe);
  }, 300);
}

export function printTableReport({
  title,
  sourcePages,
  headers,
  rows,
  filters = [],
  rowsPerPage = 20,
  sourceStartPage = 1,
  sourceTotalPages,
}: {
  title: string;
  sourcePages: string;
  headers: string[];
  rows: string[][];
  filters?: ExportFilter[];
  rowsPerPage?: number;
  sourceStartPage?: number;
  sourceTotalPages?: number;
}) {
  const pageCount = Math.max(Math.ceil(rows.length / rowsPerPage), 1);
  const generatedAt = new Date().toLocaleString();
  const activeFilters = filters.filter(({ value }) => value !== null && value !== undefined && String(value).trim() !== '');
  const sheets = Array.from({ length: pageCount }, (_, pageIndex) => {
    const pageRows = rows.slice(pageIndex * rowsPerPage, (pageIndex + 1) * rowsPerPage);
    return `
      <section class="print-sheet">
        <h1>${escapePrintHtml(title)}</h1>
        <div class="print-table-meta">
          <div><strong>Source records:</strong> ${escapePrintHtml(sourcePages)}</div>
          <div><strong>Source page:</strong> ${sourceStartPage + pageIndex}${sourceTotalPages === undefined ? '' : ` of ${sourceTotalPages}`}</div>
          <div><strong>Rows exported:</strong> ${rows.length}</div>
          ${activeFilters.map(({ label, value }) => `<div><strong>${escapePrintHtml(label)}:</strong> ${escapePrintHtml(value)}</div>`).join('')}
        </div>
        <table>
          <thead><tr>${headers.map((header) => `<th>${escapePrintHtml(header)}</th>`).join('')}</tr></thead>
          <tbody>
            ${pageRows.length > 0
              ? pageRows.map((row) => `<tr>${row.map((cell) => `<td>${escapePrintHtml(cell)}</td>`).join('')}</tr>`).join('')
              : `<tr><td colspan="${Math.max(headers.length, 1)}">No matching records.</td></tr>`}
          </tbody>
        </table>
        <div class="print-sheet-footer">
          <span>Generated ${escapePrintHtml(generatedAt)}</span>
          <span>Source page ${sourceStartPage + pageIndex}${sourceTotalPages === undefined ? '' : ` of ${sourceTotalPages}`} · Export sheet ${pageIndex + 1} of ${pageCount}</span>
        </div>
      </section>
    `;
  }).join('');

  printHtml(title, sheets);
}
