import { afterEach, describe, expect, it, vi } from 'vitest';
import { printHtml, printTableReport, setPrintAuthor } from '@/utils/print';

describe('paginated table printing', () => {
  afterEach(() => {
    setPrintAuthor(null);
    document.body.innerHTML = '';
    vi.restoreAllMocks();
    vi.useRealTimers();
  });

  it('keeps three six-row source pages on separate sheets, including a partial last page', () => {
    vi.useFakeTimers();
    vi.spyOn(HTMLIFrameElement.prototype, 'contentWindow', 'get').mockReturnValue({
      document: document.implementation.createHTMLDocument(),
      focus: vi.fn(),
    } as unknown as Window);

    printTableReport({
      title: 'Orders',
      sourcePages: 'Pages 2-4 of 4',
      sourceStartPage: 2,
      sourceTotalPages: 4,
      rowsPerPage: 6,
      headers: ['Order'],
      rows: Array.from({ length: 14 }, (_, index) => [`Order ${index + 7}`]),
    });

    const doc = document.querySelector('iframe')!.contentWindow!.document;
    const sheets = [...doc.querySelectorAll('.print-sheet')];
    expect(sheets.map((sheet) => sheet.querySelectorAll('tbody tr').length)).toEqual([6, 6, 2]);
    expect(sheets.map((sheet) => sheet.querySelector('.print-sheet-footer')!.textContent))
      .toEqual([
        expect.stringContaining('Source page 2 of 4 · Export sheet 1 of 3'),
        expect.stringContaining('Source page 3 of 4 · Export sheet 2 of 3'),
        expect.stringContaining('Source page 4 of 4 · Export sheet 3 of 3'),
      ]);
    expect(sheets[0].querySelector('tbody')!.textContent).not.toContain('Order 13');
    expect(sheets[1].querySelector('tbody')!.textContent).toContain('Order 13');
    expect(doc.querySelector('style')!.textContent).toContain('break-after: page');
  });

  it('labels each table sheet with the signed-in user and safely escapes their name', () => {
    vi.useFakeTimers();
    const doc = document.implementation.createHTMLDocument();
    vi.spyOn(HTMLIFrameElement.prototype, 'contentWindow', 'get').mockReturnValue({ document: doc, focus: vi.fn() } as unknown as Window);
    setPrintAuthor({ name: 'Ana <script>alert(1)</script>', role: 'warehouse_staff' });
    printTableReport({ title: 'Stock', sourcePages: 'Pages 1-2', rowsPerPage: 1, headers: ['Item'], rows: [['Paint'], ['Epoxy']] });
    for (const sheet of doc.querySelectorAll('.print-sheet')) {
      expect(sheet.querySelector('.print-table-meta')!.textContent).toContain('Generated by: Ana <script>alert(1)</script> (warehouse staff)');
    }
    expect(doc.querySelector('script')).toBeNull();
    expect(doc.querySelector('.footer')!.textContent).toContain('Philippine time');
  });

  it('clears attribution on logout and applies attribution to non-table PDFs too', () => {
    vi.useFakeTimers();
    const doc = document.implementation.createHTMLDocument();
    vi.spyOn(HTMLIFrameElement.prototype, 'contentWindow', 'get').mockReturnValue({ document: doc, focus: vi.fn() } as unknown as Window);
    setPrintAuthor({ name: 'Admin Name', role: 'admin' });
    printHtml('Receipt', '<h1>Receipt</h1>');
    expect(doc.querySelector('.footer')!.textContent).toContain('Admin Name (admin)');
    setPrintAuthor(null);
    printHtml('Receipt', '<h1>Receipt</h1>');
    expect(doc.querySelector('.footer')!.textContent).toContain('Unknown user');
    expect(doc.querySelector('.footer')!.textContent).not.toContain('Admin Name');
  });
});
