ALTER TABLE "deliveries"
ADD COLUMN IF NOT EXISTS "delivery_method" VARCHAR(30) NOT NULL DEFAULT 'TRUCK',
ADD COLUMN IF NOT EXISTS "batch_number" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "batch_count" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "load_kg" DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS "third_party_provider" VARCHAR(80),
ADD COLUMN IF NOT EXISTS "third_party_reference" VARCHAR(120);
